#!/usr/bin/env bash

if [ "$#" != 1 ]; then
    echo "Usage: ./push-deb DEB_FOLDER"
    exit 3
fi

package_cloud version >/dev/null 2>&1 || { echo "I require package_cloud but it's not installed. To install run 'sudo gem install package_cloud'."; exit 3; }

REPOSITORY="JonasGroeger/soundnode"
DEB_FOLDER="$1"

if [ ! -d "$DEB_FOLDER" ]; then
    echo "$DEB_FOLDER is not folder. Please provide a valid folder!"
    exit 6
fi

find "$DEB_FOLDER" -maxdepth 1 -mindepth 1 -name "soundnode_*.deb" -type f | while read DEB_FILE; do

    if file "$DEB_FILE" | grep -qv "Debian binary package"; then
        echo "$DEB_FILE is not a valid debian package!"
        exit 7
    fi

    ##########
    # Ubuntu #
    ##########
    package_cloud push "$REPOSITORY/ubuntu/trusty"  "$DEB_FILE" # 14.04 LTS
    package_cloud push "$REPOSITORY/ubuntu/xenial"  "$DEB_FILE" # 16.04 LTS
    package_cloud push "$REPOSITORY/ubuntu/yakkety" "$DEB_FILE" # 16.10

    ##########
    # Debian #
    ##########
    package_cloud push "$REPOSITORY/debian/jessie" "$DEB_FILE" # 8

    ################
    # ElementaryOS #
    ################
    package_cloud push "$REPOSITORY/elementaryos/jupiter" "$DEB_FILE" # 0.1
    package_cloud push "$REPOSITORY/elementaryos/luna"    "$DEB_FILE" # 0.2
    package_cloud push "$REPOSITORY/elementaryos/freya"   "$DEB_FILE" # 0.3

    ##############
    # Linux Mint #
    ##############
    package_cloud push "$REPOSITORY/linuxmint/qiana"   "$DEB_FILE" # 17
    package_cloud push "$REPOSITORY/linuxmint/rebecca" "$DEB_FILE" # 17.1
    package_cloud push "$REPOSITORY/linuxmint/rafaela" "$DEB_FILE" # 17.2
    package_cloud push "$REPOSITORY/linuxmint/rosa"    "$DEB_FILE" # 17.3
    package_cloud push "$REPOSITORY/linuxmint/sarah"   "$DEB_FILE" # 18

done

